Add database drawing and schema
w286432531/ai-restaurant-app pull request #2
Opened 2022-08-12 03:54 UTC by w286432531

Finish database drawing.
Add database models.

2022-08-12 05:13 UTC, linmao0991 requested changes
Over all it's a good start. There are a few things I would look over that commented on.

I might also suggest putting some comments in Prisma on the uses for some of these tables. Once it's refined you can move those comments in some kind of documentation for your schema.

2022-08-12 05:13 UTC, linmao0991 commented on prisma/schema.prisma
> +  hours String
We might want to change the types or add fields to this table. 7 days a week with possibility varying times each day. Maybe consider changing hours to `json` we can place a json object with each day and hours.

2022-08-12 05:13 UTC, linmao0991 commented on prisma/schema.prisma
> +  alternativeName String?
What is the purpose of user type? Like roles? Customer, Owner ...etc? If so what is `name` and `alternativeName` ?

2022-08-12 05:13 UTC, linmao0991 commented on prisma/schema.prisma
> +  price        Decimal       @db.Decimal(12, 2)
Although decimals are fine, consider using just an `Int` here and then you can represent prices in whole numbers. Like $1.00 would be stored as `100`. Then on the front end you can convert these with 2 decimal places when displaying them.

Why I suggest doing this way is because any type of arithmetic done to these will result in rounding errors . Here is a good read on why https://frontstuff.io/how-to-handle-monetary-values-in-javascript.

2022-08-12 21:22 UTC, w286432531 commented on prisma/schema.prisma
> +  alternativeName String?
I changed model name to role

2022-08-12 21:22 UTC, w286432531 commented on prisma/schema.prisma
> +  hours String
I changed datatype to time

2022-08-15 15:53 UTC, linmao0991 approved these changes
Looks good.

**Future stuff**
I see you are accommodating for different languages ( English, Chinese, ...etc)? If that is the case it might be good to thing about a different way to approach this rather than a field for the alternate name. Maybe a `itemName`, `ingredientName`, ...etc  and have  a 1-to-1 relationship with item and ingredients. The name tables could contain fields with each language and names of item or ingredient in each language field.

With this approach ( or something like it ) you can add more than 1 translation of the name and ingredient.

2022-08-15 22:49 UTC, merged